update neovim, i3 config and bin, add picom config

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -10,146 +10,146 @@ set -e
 echo ''
 
 info() {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+	printf "\r  [ \033[00;34m..\033[0m ] $1\n"
 }
 
 user() {
-  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+	printf "\r  [ \033[0;33m??\033[0m ] $1\n"
 }
 
 success() {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
 fail() {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+	echo ''
+	exit
 }
 
 setup_gitconfig() {
-  if ! [ -f git/gitconfig.local.symlink ]; then
-    info 'setup gitconfig'
+	if ! [ -f git/gitconfig.local.symlink ]; then
+		info 'setup gitconfig'
 
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]; then
-      git_credential='osxkeychain'
-    fi
+		git_credential='cache'
+		if [ "$(uname -s)" == "Darwin" ]; then
+			git_credential='osxkeychain'
+		fi
 
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
+		user ' - What is your github author name?'
+		read -e git_authorname
+		user ' - What is your github author email?'
+		read -e git_authoremail
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example >git/gitconfig.local.symlink
+		sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example >git/gitconfig.local.symlink
 
-    success 'gitconfig'
-  fi
+		success 'gitconfig'
+	fi
 }
 
 link_file() {
-  local src=$1 dst=$2
+	local src=$1 dst=$2
 
-  local overwrite= backup= skip=
-  local action=
+	local overwrite= backup= skip=
+	local action=
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
+	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
 
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
+		if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
 
-      local currentSrc="$(readlink $dst)"
+			local currentSrc="$(readlink $dst)"
 
-      if [ "$currentSrc" == "$src" ]; then
+			if [ "$currentSrc" == "$src" ]; then
 
-        skip=true
+				skip=true
 
-      else
+			else
 
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+				user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
         [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
+				read -n 1 action
 
-        case "$action" in
-        o)
-          overwrite=true
-          ;;
-        O)
-          overwrite_all=true
-          ;;
-        b)
-          backup=true
-          ;;
-        B)
-          backup_all=true
-          ;;
-        s)
-          skip=true
-          ;;
-        S)
-          skip_all=true
-          ;;
-        *) ;;
+				case "$action" in
+				o)
+					overwrite=true
+					;;
+				O)
+					overwrite_all=true
+					;;
+				b)
+					backup=true
+					;;
+				B)
+					backup_all=true
+					;;
+				s)
+					skip=true
+					;;
+				S)
+					skip_all=true
+					;;
+				*) ;;
 
-        esac
+				esac
 
-      fi
+			fi
 
-    fi
+		fi
 
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
+		overwrite=${overwrite:-$overwrite_all}
+		backup=${backup:-$backup_all}
+		skip=${skip:-$skip_all}
 
-    if [ "$overwrite" == "true" ]; then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
+		if [ "$overwrite" == "true" ]; then
+			rm -rf "$dst"
+			success "removed $dst"
+		fi
 
-    if [ "$backup" == "true" ]; then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
+		if [ "$backup" == "true" ]; then
+			mv "$dst" "${dst}.backup"
+			success "moved $dst to ${dst}.backup"
+		fi
 
-    if [ "$skip" == "true" ]; then
-      success "skipped $src"
-    fi
-  fi
+		if [ "$skip" == "true" ]; then
+			success "skipped $src"
+		fi
+	fi
 
-  if [ "$skip" != "true" ]; then # "false" or empty
-    echo "going to link $1 to $2"
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
+	if [ "$skip" != "true" ]; then # "false" or empty
+		echo "going to link $1 to $2"
+		ln -s "$1" "$2"
+		success "linked $1 to $2"
+	fi
 }
 
 join_by() {
-  local IFS="$1"
-  shift
-  echo "$*"
+	local IFS="$1"
+	shift
+	echo "$*"
 }
 
 install_dotfiles() {
-  info 'installing dotfiles'
+	info 'installing dotfiles'
 
-  local overwrite_all=false backup_all=false skip_all=false
+	local overwrite_all=false backup_all=false skip_all=false
 
-  for src in $(find -H "$DOTFILES_ROOT" -name '*.symlink' -maxdepth 2 -not -path '*.git*'); do
-    dst="$HOME/.$(basename "${src%.*}")"
-    link_file "$src" "$dst"
-  done
+	for src in $(find -H "$DOTFILES_ROOT" -name '*.symlink' -maxdepth 2 -not -path '*.git*'); do
+		dst="$HOME/.$(basename "${src%.*}")"
+		link_file "$src" "$dst"
+	done
 
-  folder_corresponding_structure=(config)
-  joined_white_list=$(join_by '|' "${folder_corresponding_structure[@]}")
-  for src in $(find "$DOTFILES_ROOT" -regextype egrep -regex ".*/($joined_white_list)/.*symlink"); do
-    symlink_stripped="${src%.*}"
-    dotfiles_root_stripped="${symlink_stripped#$DOTFILES_ROOT/}"
-    dst="$HOME/.$dotfiles_root_stripped"
-    dst_path="${dst%/*}"
-    if ! [[ -d $dst_path ]]; then
-      mkdir -p $dst_path
-    fi
-    link_file "$src" "$dst"
-  done
+	folder_corresponding_structure=(config i3)
+	joined_white_list=$(join_by '|' "${folder_corresponding_structure[@]}")
+	for src in $(find "$DOTFILES_ROOT" -regextype egrep -regex ".*/($joined_white_list)/.*symlink"); do
+		symlink_stripped="${src%.*}"
+		dotfiles_root_stripped="${symlink_stripped#$DOTFILES_ROOT/}"
+		dst="$HOME/.$dotfiles_root_stripped"
+		dst_path="${dst%/*}"
+		if ! [[ -d $dst_path ]]; then
+			mkdir -p $dst_path
+		fi
+		link_file "$src" "$dst"
+	done
 }
 
 # setup_gitconfig
